### ISSUE TITLE
Downloading latest build vs. building from source

### ISSUE THREAD

**Issue by patricknelson** [Gerrit-K/ytt-docker#1]
Not an issue per se, but I'm just curious (since I'm also integrating `ytt` into one of my docker images as well, in my case based on `gcloud-sdk`). I saw this image/repo and was considering going this route as an alternative (building from source). However, currently this is what I'm doing:

```Dockerfile
# Add YTT to help with compiling YAML templates. In this case, we'll attempt to get the latest available release.
RUN curl -L -o ytt https://github.com/k14s/ytt/releases/latest/download/ytt-linux-amd64 \
	&& chmod +x  ytt \
	&& mv ytt /usr/local/bin
```

Is there an advantage to building from source vs. referencing the latest release already compiled version hosted in Github's releases area? I figured this might be a little easier to maintain and less fickle (in case dependencies change in the future) since all you'd have to do is maybe update the URL, as long as the author keeps posting updated binaries.

**Comment by Gerrit-K** [comment]
Hi @patricknelson, thanks for your feedback! In general you're right. Whenever there is a precompiled binary for the target system, it's usually less error prone to use this instead of compiling from source. However, sometimes there isn't and that's where this image originated.

Before I started this, I was looking for a way to get ytt running on arm systems (like a raspberry pi) as well. Instead of asking the k14s team for precompiled arm binaries, I figured I could also use docker for that, so I started a simple Dockerfile. I knew that simply adding an x64 binary to an arm base image wouldn't work, which is why I went with the current approach of compiling the sources. What I didn't know was that it would become rather difficult to setup the docker hub build agents to produce arm images in addition to the usual x64 images. I tried a couple of hours but ran out of spare time for that project. After more time went by, I realized that I don't even use ytt on my work machine (let alone on my raspberry pi), so I've neglected this almost completely. 

The only reasons why this is still published is that (1) it was already there and I thought it might help someone else who is looking for a slim (x64) ytt image and (2) updating the image is currently as simple as `git tag <ytt-version> master && git push origin --tags`, I don't even have to touch the code. The major downside however is that there is _absolutely no QA_ for this image. I don't have any automated tests implemented and I don't even use this image myself, so if something goes wrong, I'll most likely only know about it if someone reports an issue. If you (or someone else) depend(s) on this image, it might be worth checking out the new [official k14s image](https://hub.docker.com/r/k14s/image) ([sources](https://github.com/k14s/docker-image)), which includes ytt as well as other tools from their stack.

**Comment by patricknelson** [comment]
Alright, thanks for the history and explanation. I don’t depend on it yet, I was initially just curious about the pros/cons of incorporating precompiled binary vs. compiling, wondering if there was a better method for my use case. Probably over planning/engineering on my part 😄.

I don’t know much about working with Docker Hub (nor the advantages of just using them to perform builds). Have you tried Travis CI to do the builds for you? I have a small amount of experience with it and I know it’s fairly easy to use. I’m guessing you could build there and then push up to Docker Hub (would likely just need to add a `docker login ...` step with some env vars).  Probably not worth trying now, but potentially useful down the line in case you ever need to go that route again. One thing I know all too well is banging head against the desk for hours on end only give up and go an alternate route and solve the problem is 1/5th the time I just wasted!

**Comment by Gerrit-K** [comment]
@patricknelson thanks for the hint on Travis CI! I honestly didn't think of outsourcing the build to a different provider yet. It seems that there is [multiarch build support (alpha)](https://docs.travis-ci.com/user/multi-cpu-architectures/) and I'll definitely take a look into that, once I'll come back to this (or a similar) problem 👍 
And your last sentence sounds painfully familiar ... 😅

**Comment by patricknelson** [comment]
Hey, glad I could help! The concept of "stop loss" really works well in the world of programming. Every once in a while that worthwhile bullheadedness has to be put aside for a moment where you step back and say "Is there a way around this boulder instead of trying to drill a tunnel through it?" 🤔
