### ISSUE TITLE
Access website

### ISSUE THREAD

**Issue by irtazas** [Gerrit-K/ytt-docker#2]
Is it possible to access the website with` ytt website`?
I tried everything but no success. Any hints?

**Comment by Gerrit-K** [comment]
Hi @IrtazaS. Good point, I didn't know that command. It's true that it doesn't work, because the Dockerfile simply builds the binary without website assets (see [this part of the official build.sh](https://github.com/k14s/ytt/blob/bf36d27313edd2439aa72664f216b4ffcc377ce8/hack/build.sh#L15-L18)).

I think I should be able to add it without too much effort, but that might increase the size of the final Docker image, weakening one of its strong points. Do you have a specific use-case that requires this (instead of using the online documentation) or would it be just for convenience?

**Comment by irtazas** [comment]
Thanks @Gerrit-K for pointing this out! 
I am using your docker image for yaml API templating. I was just wondering why the website isn't available. Thanks for the reply, definitely a big help!

**Comment by Gerrit-K** [comment]
Hey @IrtazaS I think I have found a solution, but it isn't a pretty one ... 
There were two major issues with the `ytt` code:
1. [The default listen address is `localhost:8080`](https://github.com/k14s/ytt/blob/582ad9ca849559e5d75b680b1831105059a0e953/pkg/cmd/website.go#L36) which means that if it's run inside a container, it won't accept any connections from the outside.
2. The server uses a HTTPS redirect which is only skipped [if a client connects from `127.0.0.1`](https://github.com/k14s/ytt/blob/ca84ba5146ef8679041019df0113f65b93d2521d/pkg/website/server.go#L157-L159), so again, related to the docker networking.

I've now added a "hack" by changing the source code in these two sections, but it feels really ugly and might break in the future if the upstream code changes. You can test these changes by running `docker run --rm -p 8080:8080 gerritk/ytt:fix-2-website website`.

Let me know if it works (and if you think that the website feature is important enough for this hack to be merged). I would also recommend to create an issue at [k14s/docker-image](https://github.com/k14s/docker-image), which holds the official docker image that is currently unable to serve the website as well, due to the same reasons.

**Comment by irtazas** [comment]
thanks @Gerrit-K works like a charm!

**Comment by Gerrit-K** [comment]
Alright. I've merged this and updated the `latest` build, but won't change any of the existing versions. Future versions will however have this fix. Also, feel free to follow the upstream issue I've created.

**Comment by Gerrit-K** [comment]
@IrtazaS fyi: there was an upstream change that introduced a new flag: `--redirect-to-https`. With that change, I was now able to run the website without my hacks, so I removed them again. I had to change the docker command slightly though (see the `README.md`). The `latest` and all future version tags will include this fix 😉

**Comment by irtazas** [comment]
that's wonderful! Thanks for your help @Gerrit-K 
Really appreciate it.
